// Code generated by "stringer -linecomment -type FrameType"; DO NOT EDIT.

package pe

import "strconv"

const _FrameType_name = "FPOTrapTSSNonFPO"

var _FrameType_index = [...]uint8{0, 3, 7, 10, 16}

func (i FrameType) String() string {
	if i >= FrameType(len(_FrameType_index)-1) {
		return "FrameType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FrameType_name[_FrameType_index[i]:_FrameType_index[i+1]]
}
